language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-base-gen' ]; then cd .. && eval "mv $currentfolder generator-base-gen" && cd generator-base-gen; fi

